# MODEL CONFIG FILE
# This file contains parameters that can be changed by a user.

# MODEL AND DATA YEARS
# These parameters determine what year the outputs represent and which years of data
# are used from each source

# The target year is used to determine the temporal correlation of data with the
# electricity generation processes, which can be used in uncertainty calculations.
electricity_lci_target_year: 2018

# Select a regional aggregation from "eGRID", "NERC", "BA", "US", "FERC", and "EIA"
# The EPA_eGRID trading method can only be used with "eGRID".
# The NETL_BA_trading method can only be used with "BA" and "FERC"
regional_aggregation: 'eGRID'

# If egrid is not used as a primary data source then set "replace_egrid" to True. This
# will trigger the use of EPA CEMS and EIA data as substitutes for eGRID.
egrid_year: 2014
eia_gen_year: 2017
replace_egrid: False

# NETL has developed an alternate method for generation process calculations. While
# this `alt_generation` method is faster, the uncertainty calculations are different
# from the original EPA version. This method cannot be used with eGRID regions
use_alt_gen_process: False

# Upstream data from NETL can be included in the outputs
include_upstream_processes: False

inventories_of_interest:
  eGRID: 2014
  TRI: 2014
  NEI: 2014
  RCRAInfo: 2013


# GENERATOR FILTERS
# These parameters determine if any power plants are filtered out
include_only_egrid_facilities_with_positive_generation: True
filter_on_efficiency: True
egrid_facility_efficiency_filters:
  lower_efficiency: 10
  upper_efficiency: 100

# ELCI creates life cycle processes for each fuel type. If you only want to include
# power plants with a minumum amount of generation from a single fuel make sure this
# parameter is set to True
filter_on_min_plant_percent_generation_from_primary_fuel: True
min_plant_percent_generation_from_primary_fuel_category: 90

# NEEDS A GOOD DESCRIPTION OF THIS PARAMETER
filter_non_egrid_emission_on_NAICS: True


# TRANSMISSION AND ELECTRICITY TRADING
# These parameters are used to determine which method of electricity trading is used
# and what losses from electricity distribution are included in the results.

# Should this be transmission grid?
efficiency_of_distribution_grid: 0.95

# Electricity trading can be calculated using a method from EPA (with or without a
# surplus trading pool) that is based on eGRID regions or a method from NETL that
# uses an input-output approach using exchange data between balancing authorities
# from EIA.

EPA_eGRID_trading: True
net_trading: False

NETL_IO_trading: False
NETL_IO_trading_year: 2016



# OTHER PARAMETERS

fedelemflowlist_version: 0.1
post_process_generation_emission_factors: False
use_primaryfuel_for_coal: False
fuel_name_file: fuelname_1.csv
